### ISSUE TITLE
lt spice labelled node is converted to a ground element

### ISSUE THREAD

**Issue by mp8g16** [Steffen-W/Convert_LTspice_to_Latex#1]
When  a schematic containing a net name label is converted into tikz the node is converted into a ground node.

![Draft](https://user-images.githubusercontent.com/34187699/77856489-71e24c80-71ef-11ea-8521-1a683889ff3a.png)
![Drafttex](https://user-images.githubusercontent.com/34187699/77856491-760e6a00-71ef-11ea-80a4-e10f3d644746.png)

**Comment by Steffen-W** [comment]
Hello, please excuse me for not looking into this for a long time. I have now adjusted the functionality.
